# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c62d0dd4313b9f752ec0a6b29705ed1c21f7ffa91304ad4937c965efc76abb4461939a16a1a3d966156c3cba90006e16a63f0e48b85557e3ae9d883bad74cc9
  aws_access_key_id: AKIAJMKZFYDRUDEZFXBA
  aws_secret_access_key: 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

test:
  secret_key_base: 02083fd52835f6fb7f752a9197e9e70dbdb5617b6a8f05f6d549870c0f403442927fcd92face9e16e6bb3ccec7c2909dcb6340568661bbcfce7135102e79ed25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
